In [10]:
list1 = list(range(10000000))

In [11]:
%time for i in list1: i*5

CPU times: user 995 ms, sys: 0 ns, total: 995 ms
Wall time: 993 ms
Compiler : 148 ms


In [12]:
import numpy as np

In [13]:
a= np.arange(10000000)

In [14]:
%time a*5

CPU times: user 20.3 ms, sys: 32.4 ms, total: 52.7 ms
Wall time: 51.1 ms


array([       0,        5,       10, ..., 49999985, 49999990, 49999995])

In [15]:
z= np.zeros((2,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
z= np.zeros((2,2,2,4))
z
#list1

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
o =  np.ones((4,5))
o

In [19]:
empty = np.empty((2,2))
empty

array([[0., 0.],
       [0., 0.]])

In [21]:
ranges = np.arange(10)
ranges

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
list1 = [[1,2,0],[3,4,30],[5,6,10],[7,8,9]]
a=np.array(list1)
a

array([[ 1,  2,  0],
       [ 3,  4, 30],
       [ 5,  6, 10],
       [ 7,  8,  9]])

In [23]:
a[1,2]

30

In [25]:
a=[[[1,3],[2,4],[5,6]],
   [[11,33],[22,44],[55,66]]]
a = np.array(a)
a

array([[[ 1,  3],
        [ 2,  4],
        [ 5,  6]],

       [[11, 33],
        [22, 44],
        [55, 66]]])

In [26]:
a[0,1,0]

2

In [27]:
a[0,2,1]

6

In [28]:
a.shape

(2, 3, 2)

In [29]:
a[1,1,1]

44

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Odd numbers from 1 to 100
# Even numbers from 1 to 100

In [31]:
2*np.arange(0,49) +1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

In [ ]:
np.arange(1,100,2)

In [32]:
7*np.arange(1,11)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [33]:
a=[[[1,3],[2,4],[5,6]],
   [[11,33],[22,44],[55,66]]]
a = np.array(a)
a

array([[[ 1,  3],
        [ 2,  4],
        [ 5,  6]],

       [[11, 33],
        [22, 44],
        [55, 66]]])

In [34]:
a[0]

array([[1, 3],
       [2, 4],
       [5, 6]])

In [35]:
a[0][2]

array([5, 6])

In [36]:
a[0][2][1]

6

In [ ]:
a

In [37]:
a[0:3:2]

array([[[1, 3],
        [2, 4],
        [5, 6]]])

In [38]:
a[:,0:3:2,:]

array([[[ 1,  3],
        [ 5,  6]],

       [[11, 33],
        [55, 66]]])

In [39]:
b=a[0]

In [40]:
b

array([[1, 3],
       [2, 4],
       [5, 6]])

In [41]:
b[0:2]

array([[1, 3],
       [2, 4]])

In [42]:
b[::2]

array([[1, 3],
       [5, 6]])

In [43]:
b

array([[1, 3],
       [2, 4],
       [5, 6]])

In [44]:
b[1:3]

array([[2, 4],
       [5, 6]])

In [45]:
b[2:]

array([[5, 6]])

In [46]:
b[:]

array([[1, 3],
       [2, 4],
       [5, 6]])

In [47]:
b[1,:]

array([2, 4])

In [48]:
b

array([[1, 3],
       [2, 4],
       [5, 6]])

In [49]:
b[:,1]

array([3, 4, 6])

In [ ]:
'''
[11111]
[10001]
[10001]
[10001]
[11111]

'''


In [50]:
a =np.zeros((5,5))

In [51]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
a[0,:]  = 1

In [53]:
a

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
a[:,4] = 1

In [57]:
a

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
a=np.ones((5,5))
a[1:4,1:4]=0

In [59]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
'''
Checker board
10101010
01010101
10101010
01010101
10101010
01010101
10101010
01010101

'''

In [60]:
t=np.zeros((8,8))
t

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
t[::2,::2]=1

t

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
t[1::2,1::2]=1
t

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [62]:
#Football ground
'''
1111111111
0000000000
1111111111
0000000000
1111111111
0000000000
1111111111
0000000000
1111111111
0000000000


'''

'\n1111111111\n0000000000\n1111111111\n0000000000\n1111111111\n0000000000\n1111111111\n0000000000\n1111111111\n0000000000\n\n\n'

In [63]:
b

array([[1, 3],
       [2, 4],
       [5, 6]])

In [ ]:
b[1,:]

In [64]:
b.shape

(3, 2)

In [65]:
b.dtype

dtype('int64')

In [66]:
c=b.astype('float64')

In [67]:
c.dtype

dtype('float64')

In [68]:
b.ndim

2

In [69]:
z=np.zeros((6,4)).reshape(2,12)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
z.reshape(4,3,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [72]:
b

array([[1, 3],
       [2, 4],
       [5, 6]])

In [73]:
b*2

array([[ 2,  6],
       [ 4,  8],
       [10, 12]])

In [74]:
1/b

array([[1.        , 0.33333333],
       [0.5       , 0.25      ],
       [0.2       , 0.16666667]])

In [75]:
b+b

array([[ 2,  6],
       [ 4,  8],
       [10, 12]])

In [76]:
b**2

array([[ 1,  9],
       [ 4, 16],
       [25, 36]])

In [77]:
b<3

array([[ True, False],
       [ True, False],
       [False, False]])

In [78]:
b[b<3]

array([1, 2])

In [7]:
names=np.array(['Arham','Jawed','Akbar','Abdul Waheed'])
ages = np.array([22,25,27,59])

In [79]:
names[ages>50]

array(['Abdul Waheed'], dtype='<U12')

In [80]:
names

array(['Arham', 'Jawed', 'Akbar', 'Abdul Waheed'], dtype='<U12')