In [152]:
# Revision

In [1]:
import numpy as np

In [2]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
a[1,0] 

3

In [8]:
a[1][0]

3

In [11]:
arr = np.random.randn(10,10)
arr

array([[-0.85585557,  1.08919009, -0.29535019, -0.22155502, -1.55921162,
        -0.01673087, -1.33256385,  0.02745428,  0.3509972 ,  0.48670246],
       [ 0.96301269, -1.60426481, -1.07414606,  1.0420112 ,  0.20706374,
        -0.87821287, -0.43742905,  0.98930594, -0.18043793, -0.29693696],
       [-0.01782194, -0.25322169, -0.24143443,  0.06626357,  1.52233244,
        -0.54413794,  0.12868126, -2.27184427, -0.12118297, -1.45685168],
       [-1.56567093, -0.87323115, -0.66651968,  0.61805122, -0.35423407,
         2.47632457,  1.41415491, -0.18357943, -0.99895027,  0.13211769],
       [ 0.28426243, -0.47930026, -0.59504886, -0.33007486, -0.12631542,
         1.18856109, -0.0032401 ,  1.16522408, -1.28179669, -0.58482494],
       [-0.46648118, -0.38256044,  0.12590161, -0.81798657, -1.5960836 ,
         2.09385343, -0.95553991,  2.08434593,  0.61680345, -0.50244873],
       [-0.63822262, -0.34822356,  0.05273823, -0.79377328,  0.57443325,
         0.14236463, -0.37684832,  1.59527195

In [12]:
arr[0,:]

array([-0.85585557,  1.08919009, -0.29535019, -0.22155502, -1.55921162,
       -0.01673087, -1.33256385,  0.02745428,  0.3509972 ,  0.48670246])

In [13]:
'''
0000000000
0111111110
0111111110
0111111110
0111111110
0111111110
0000000000
'''

'\n0000000000\n0111111110\n0111111110\n0111111110\n0111111110\n0111111110\n0000000000\n'

In [14]:
a = np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
a[1:-1,1:-1] = 1
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#checkerboard pattern
'''
10101010
01010101
10101010
01010101
10101010
01010101
10101010
01010101
'''

In [18]:
checker = np.zeros((8,8))
checker

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
checker[0:8:2,0:8:2] = 1
checker

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
checker[1:8:2,1:8:2] =1
checker

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [ ]:
'''
000000000
111101111
111101111
111101111
111101111
111101111
111101111
111101111
111101111

'''

In [30]:
t = np.ones((9,9))

In [31]:
t[:,4] = 0
t

array([[1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.]])

In [32]:
t[0,:] = 0
t

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.]])

In [ ]:
'''
011111110
011111110
011111110
011111110
011111110
011111110
011111110
011111110
000000000
'''

In [33]:
u = np.ones((9,9))

In [34]:
u[:,0]=0
u

array([[0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
u[:,8]=0
u

array([[0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [29]:
u[8,:]=0
u

array([[0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
'''
011111111
011111111
011111111
011111111
011111111
011111111
011111111
011111111
000000000
'''

'\n011111111\n011111111\n011111111\n011111111\n011111111\n011111111\n011111111\n011111111\n000000000\n'

In [37]:
n=np.ones((9,9))
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
n[:,0]=0
n

array([[0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
n[8,:]=0
n

array([[0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
'''
011111110
101111101
110111011
111010111
111101111
011111111
011111111
011111111
000000000
'''

'\n011111110\n101111101\n110111011\n111010111\n111101111\n011111111\n011111111\n011111111\n000000000\n'

In [42]:
cross = np.ones((10,10))
cross

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
cross[a,a] = 0

In [49]:
cross

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [51]:
b = np.arange(9,-1,-1)
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [52]:
cross[a,b] = 0
cross

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [57]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
a.mean()

5.5

In [59]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [60]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [61]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

# np.sum() --count of True values
# np.all() -- True when all values are True
# np.any() -- True if any one value is True

In [62]:
jungle = np.array(['lion', 'horse','lion','peacock','lion','elephant'])
jungle

array(['lion', 'horse', 'lion', 'peacock', 'lion', 'elephant'],
      dtype='<U8')

In [65]:
boolean = jungle =='lion'

In [66]:
boolean.sum() #sum of lions

3

In [69]:
boolean_donkey = jungle == 'donkey'
boolean_donkey.any()

False

In [70]:
boolean_pk = jungle == 'peacock'
boolean_pk.any()

True

In [71]:
boolean_ln = jungle == 'lion'
boolean_ln.all()

False

In [72]:
arr = np.array([16,50,210,280])
arr

array([ 16,  50, 210, 280])

In [73]:
boolean_even = arr%2 == 0
boolean_even.all()

True

In [77]:
names = np.array(['ali','noman','ahmed','asif'])
bool_nm = names == 'ali'
bool_nm.any()

True

In [81]:
np.sort(names)

array(['ahmed', 'ali', 'asif', 'noman'], dtype='<U5')

In [83]:
np.unique(jungle)

array(['elephant', 'horse', 'lion', 'peacock'], dtype='<U8')

# Save and Load Numpy Arrays

In [84]:
np.save("jungle.npy",jungle)

In [85]:
load_jungle = np.load("jungle.npy")
load_jungle

array(['lion', 'horse', 'lion', 'peacock', 'lion', 'elephant'],
      dtype='<U8')

In [86]:
np.savez("multiple.npz",a = jungle, b=names,c = arr) #arbitrary keys

In [88]:
arrays = np.load("multiple.npz")

In [90]:
arrays['a']

array(['lion', 'horse', 'lion', 'peacock', 'lion', 'elephant'],
      dtype='<U8')

In [91]:
arrays['b']

array(['ali', 'noman', 'ahmed', 'asif'], dtype='<U5')

In [92]:
arrays['c']

array([ 16,  50, 210, 280])

In [ ]:
# make 3 arrays 1 of numbers 1-10, 2nd of even numbers 1-10
# 3rd of odd numbers 1-10

In [93]:
nums = np.arange(1,11)
even = np.arange(2,11,2)
odds = np.arange(1,11,2)
print(nums,even,odds)

[ 1  2  3  4  5  6  7  8  9 10] [ 2  4  6  8 10] [1 3 5 7 9]


In [94]:
np.savez("numbers.npz", n = nums, e = even, o = odds )

In [95]:
all_arrays = np.load("numbers.npz")

In [96]:
all_arrays['e']

array([ 2,  4,  6,  8, 10])

# Linear Algebra

In [100]:
x= np.random.randn(2,5)
y= np.random.randn(5,4)

In [101]:
x

array([[ 0.46365967, -0.70916343,  0.8861348 , -1.51545463, -1.06882101],
       [-0.96866073, -0.83161699,  0.07475441,  0.10607332, -0.16002011]])

In [102]:
y

array([[ 0.83528258,  0.34453289,  1.39026192,  0.54278163],
       [-1.31366331, -0.38257827, -0.93849401, -0.52244315],
       [ 0.54388015, -0.46708351, -1.77550452, -1.59228778],
       [ 0.32732967, -0.83430775,  1.25925843, -1.75417561],
       [ 0.72334931, -1.03349182,  0.98374737, -0.40483322]])

In [105]:
x.dot(y) #dot product
z= np.random.randn(4,4)
z

array([[-0.5640343 , -0.51748266,  0.50461658, -1.28013029],
       [ 0.41932541, -0.23573534,  0.26616366, -0.45798501],
       [ 0.00746253, -2.12913547,  0.16643985, -0.13411317],
       [ 0.78091689, -1.6032321 , -0.00516098,  0.55336923]])

In [107]:
np.diag(z) #diagonal elements

array([-0.5640343 , -0.23573534,  0.16643985,  0.55336923])

In [109]:
x = np.arange(1,5)
x

array([1, 2, 3, 4])

In [112]:
y = np.arange(6,10).reshape(4,1)
y

array([[6],
       [7],
       [8],
       [9]])

In [113]:
x.dot(y)

array([80])

In [114]:
np.linalg.eig(z) #eigen vector (energy of matrix)

(array([-0.39602846+1.07810305j, -0.39602846-1.07810305j,
        -0.07737632+0.j        ,  0.78947267+0.j        ]),
 array([[ 0.54486954+0.12496415j,  0.54486954-0.12496415j,
         -0.13523154+0.j        , -0.28181643+0.j        ],
        [ 0.15516569-0.29756283j,  0.15516569+0.29756283j,
          0.08013154+0.j        , -0.23570366+0.j        ],
        [ 0.63267912+0.j        ,  0.63267912-0.j        ,
          0.91212713+0.j        ,  0.66134392+0.j        ],
        [ 0.22040553-0.35499247j,  0.22040553+0.35499247j,
          0.37857029+0.j        ,  0.65394763+0.j        ]]))

In [115]:
z

array([[-0.5640343 , -0.51748266,  0.50461658, -1.28013029],
       [ 0.41932541, -0.23573534,  0.26616366, -0.45798501],
       [ 0.00746253, -2.12913547,  0.16643985, -0.13411317],
       [ 0.78091689, -1.6032321 , -0.00516098,  0.55336923]])

In [117]:
np.trace(z) #sum of diagonal elements

-0.07996057452309802

# Random No.s and their distributions

In [119]:
np.random.gamma((2,2)) #Gamma is distribution

array([0.78621434, 4.01215489])

In [126]:
np.random.seed(123) # A particular seed generates same sequence of random no.s (for repeatable)
np.random.normal((4,4)) #Normal is another distribution

array([2.9143694 , 4.99734545])

# Reshaping & 'C' order 'F' Order

In [127]:
a = np.zeros((4,1000000))

In [129]:
b = a.reshape(5,10,-1)
b.shape

(5, 10, 80000)

In [134]:
arr = np.arange(1,10).reshape((3,3),order = 'F')

In [135]:
arr

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Concatenation

In [139]:
#vertical
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [141]:
b = np.arange(11,31).reshape(4,5)
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [142]:
np.concatenate((a,b), axis = 0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [144]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [145]:
np.r_[a,b]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [146]:
#horizontal 
a = np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [148]:
b = np.arange(11,31).reshape(5,4)
b

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [149]:
np.concatenate((a,b),axis=1)

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18],
       [ 5,  6, 19, 20, 21, 22],
       [ 7,  8, 23, 24, 25, 26],
       [ 9, 10, 27, 28, 29, 30]])

In [150]:
np.hstack((a,b))

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18],
       [ 5,  6, 19, 20, 21, 22],
       [ 7,  8, 23, 24, 25, 26],
       [ 9, 10, 27, 28, 29, 30]])

In [151]:
np.c_[a,b]

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18],
       [ 5,  6, 19, 20, 21, 22],
       [ 7,  8, 23, 24, 25, 26],
       [ 9, 10, 27, 28, 29, 30]])