In [2]:
import numpy as np

In [3]:
x = np.array([4,8,9,10,15]) #made array using list

In [4]:
x[4]

15

In [5]:
x>5

array([False,  True,  True,  True,  True])

In [6]:
x[x>5] #passed on boolean to x itself. now it will show which elements are > 5

array([ 8,  9, 10, 15])

In [9]:
x[[2,1]] #this is called fancing indexing

array([9, 8])

In [10]:
x=np.random.randn(10,10)

In [11]:
x

array([[-0.5708737 ,  1.95338781, -0.39166688, -0.66185655, -0.00348553,
        -1.47773663, -0.85182475, -1.46220918,  2.05454244, -1.33458029],
       [-0.39292569,  0.09385884, -0.77124237, -1.06063177, -1.23516031,
        -0.55366202,  0.87694192,  0.77174904, -0.8855027 , -0.79611863],
       [-1.03442462,  0.10675667, -0.99758787, -0.6164984 ,  0.69860127,
        -0.88958208,  0.15634104, -0.25255295, -0.15794914, -2.28836458],
       [ 0.13792665, -0.51819549, -0.12025915,  0.73543038,  0.3630615 ,
        -1.29733802,  0.66979757,  2.73315322, -0.51335009,  1.91080052],
       [ 0.56637726, -0.94690803,  0.41250245, -1.53624357, -1.76750129,
        -1.05040851,  0.04110985, -0.17522451,  0.28075979,  0.43710008],
       [ 1.71674305, -0.91506851,  1.94243592, -0.07077554, -2.11829   ,
         1.87120679,  0.68043464, -0.43316998, -0.27158051, -0.8916338 ],
       [-0.41345905, -1.59009657,  0.23033683,  0.22494218, -0.54266612,
         1.02746446, -0.40092876, -0.37565896

In [12]:
x[0]

array([-0.5708737 ,  1.95338781, -0.39166688, -0.66185655, -0.00348553,
       -1.47773663, -0.85182475, -1.46220918,  2.05454244, -1.33458029])

In [14]:
x[0][4] #we will have 1st row's fifth element as o/p

-0.0034855306454235372

In [15]:
x[1:10:2]  # we want odd elements. so 1to 10 with step size 2 and of every column will be the o/p

array([[-0.39292569,  0.09385884, -0.77124237, -1.06063177, -1.23516031,
        -0.55366202,  0.87694192,  0.77174904, -0.8855027 , -0.79611863],
       [ 0.13792665, -0.51819549, -0.12025915,  0.73543038,  0.3630615 ,
        -1.29733802,  0.66979757,  2.73315322, -0.51335009,  1.91080052],
       [ 1.71674305, -0.91506851,  1.94243592, -0.07077554, -2.11829   ,
         1.87120679,  0.68043464, -0.43316998, -0.27158051, -0.8916338 ],
       [ 1.00031129, -0.60477783, -0.2320907 ,  0.51631953, -1.42704976,
        -0.31051342, -0.29174992, -0.46689482, -0.85088531, -0.80095533],
       [ 1.43193026, -0.69921245, -1.81060821,  2.18623008, -0.04566991,
         1.10690998,  0.35037926, -1.22335142, -1.2807654 , -0.19750676]])

In [19]:
x[::,0:4] #will give all rows but 0 to 4 columns

array([[-0.5708737 ,  1.95338781, -0.39166688, -0.66185655],
       [-0.39292569,  0.09385884, -0.77124237, -1.06063177],
       [-1.03442462,  0.10675667, -0.99758787, -0.6164984 ],
       [ 0.13792665, -0.51819549, -0.12025915,  0.73543038],
       [ 0.56637726, -0.94690803,  0.41250245, -1.53624357],
       [ 1.71674305, -0.91506851,  1.94243592, -0.07077554],
       [-0.41345905, -1.59009657,  0.23033683,  0.22494218],
       [ 1.00031129, -0.60477783, -0.2320907 ,  0.51631953],
       [ 0.7152033 ,  1.31193533,  0.14838248,  0.69163887],
       [ 1.43193026, -0.69921245, -1.81060821,  2.18623008]])

In [18]:
x

array([[-0.5708737 ,  1.95338781, -0.39166688, -0.66185655, -0.00348553,
        -1.47773663, -0.85182475, -1.46220918,  2.05454244, -1.33458029],
       [-0.39292569,  0.09385884, -0.77124237, -1.06063177, -1.23516031,
        -0.55366202,  0.87694192,  0.77174904, -0.8855027 , -0.79611863],
       [-1.03442462,  0.10675667, -0.99758787, -0.6164984 ,  0.69860127,
        -0.88958208,  0.15634104, -0.25255295, -0.15794914, -2.28836458],
       [ 0.13792665, -0.51819549, -0.12025915,  0.73543038,  0.3630615 ,
        -1.29733802,  0.66979757,  2.73315322, -0.51335009,  1.91080052],
       [ 0.56637726, -0.94690803,  0.41250245, -1.53624357, -1.76750129,
        -1.05040851,  0.04110985, -0.17522451,  0.28075979,  0.43710008],
       [ 1.71674305, -0.91506851,  1.94243592, -0.07077554, -2.11829   ,
         1.87120679,  0.68043464, -0.43316998, -0.27158051, -0.8916338 ],
       [-0.41345905, -1.59009657,  0.23033683,  0.22494218, -0.54266612,
         1.02746446, -0.40092876, -0.37565896

# making a square with borders having 1s

In [21]:
x=np.ones((5,5))

In [22]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
x[1:4,0:3]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
x[1:-1,1:-1]=0

In [37]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# checkborad

In [80]:
y=np.ones((5,5))

In [81]:
y[::,1:4:2]=0

In [82]:
y

array([[1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.]])

In [83]:
y[1:4:2,1:4:2]=1


In [84]:
Y

NameError: name 'Y' is not defined

In [85]:
y

array([[1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.]])

In [88]:
y[1:4:2,0:-1:2]=0

In [89]:
y

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.]])

In [90]:
y[1:4:2,::]=0

In [91]:
y

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [92]:
z=np.ones((10,10))

In [93]:
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [94]:
z[0::2,1::2]=0
z[1::2,0::2]=0
z

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])