In [1]:
import numpy as np

In [2]:
x =np.zeros((4,4))

In [3]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.empty(7,7)

TypeError: data type not understood

In [6]:
np.empty((7,7))

array([[1.60219035e-306, 3.60116092e+228, 6.32404027e-322,
        7.94822228e-300, 7.94822228e-300, 7.92568800e-300,
        7.94822419e-300],
       [3.07308832e-321, 2.02369289e-320, 5.94158822e-313,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.04706795e-306],
       [9.34600963e-307, 1.37961302e-306, 1.42410974e-306,
        4.17524795e+199, 6.32404027e-322, 7.94822228e-300,
        7.94822228e-300],
       [7.92568800e-300, 7.94822419e-300, 5.62740771e-321,
        2.02369289e-320, 5.94158822e-313, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.04706795e-306, 9.34600963e-307,
        7.56593017e-307, 1.42410974e-306, 2.75605791e+265,
        6.71929278e-322],
       [7.94822228e-300, 7.94822228e-300, 7.92568800e-300,
        7.94822419e-300, 7.30229025e-321, 2.02369289e-320,
        8.91238232e-313],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.04706795e-306, 9.34600963e-307, 9.34598925e-307,
        1.11261434

In [7]:
//np.empt se kch b data aa skta h bs jo desied size dia h humne usi ki hgi

SyntaxError: invalid syntax (<ipython-input-7-f9211d8c95c4>, line 1)

In [10]:
#np.empt se kch b data aa skta h bs jo desied size dia h humne usi ki hgi

In [11]:
l = [2,3,5,6] #list

In [12]:
np.array(l) # converting that list into numpy array

array([2, 3, 5, 6])

In [14]:
x =np.arange(1,100,10)

In [15]:
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [16]:
x.shape()

TypeError: 'tuple' object is not callable

In [17]:
x.shape

(10,)

In [18]:
z=np.zeros((10,10))

In [19]:
z.shape

(10, 10)

In [20]:
Z

NameError: name 'Z' is not defined

In [21]:
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
y=z.reshape((2,2,5,5))

In [23]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [24]:
y.dtype

dtype('float64')

In [25]:
y.ndim

4