In [1]:
import numpy as np

In [2]:
a = np.random.randn(10)

In [3]:
b = np.random.randn(10)

In [4]:
a

array([-1.15045133,  0.44714755,  1.36829133,  0.71787909, -0.809341  ,
        0.87301367, -0.90700405, -1.00216252,  1.01573066,  1.43594092])

In [5]:
b

array([ 0.3627346 , -2.69513292, -0.22151637,  1.12365595,  0.68140142,
       -0.43677363, -1.43345513,  0.03882162,  0.68803411, -1.29148084])

In [6]:
a+b

array([-0.78771673, -2.24798537,  1.14677496,  1.84153503, -0.12793958,
        0.43624004, -2.34045917, -0.96334089,  1.70376477,  0.14446008])

In [7]:
a-b

array([-1.51318593,  3.14228046,  1.5898077 , -0.40577686, -1.49074242,
        1.3097873 ,  0.52645108, -1.04098414,  0.32769655,  2.72742176])

In [8]:
2*a

array([-2.30090265,  0.89429509,  2.73658266,  1.43575817, -1.618682  ,
        1.74602735, -1.81400809, -2.00432503,  2.03146133,  2.87188184])

In [9]:
1/a

array([-0.86922408,  2.23639827,  0.73083851,  1.39299224, -1.23557314,
        1.14545743, -1.10253091, -0.99784215,  0.98451296,  0.69640748])

In [10]:
a>0

array([False,  True,  True,  True, False,  True, False, False,  True,
        True])

In [11]:
a[a>0]

array([0.44714755, 1.36829133, 0.71787909, 0.87301367, 1.01573066,
       1.43594092])

In [13]:
list2 = range(10000000)

In [17]:
%time for i in list2: i*7

Wall time: 2.85 s


In [18]:
x = np.zeros((10,10))

In [19]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
x[:,0]=-1

In [21]:
x

array([[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
x[:,-1]=2
x

array([[-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.]])

In [23]:
x[:,-5]=-5
x

array([[-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.]])

In [24]:
x[2,:]=10
x

array([[-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.]])

In [29]:
x[2:-3,2:-4]=13
x

array([[-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [-1.,  0., 13., 13., 13., 13., 13., 13.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0., -5.,  0.,  0.,  0.,  2.]])